# Generated by Django 5.2.7 on 2025-12-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_options_product_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=255,
                unique=True,
                verbose_name="URL-идентификатор",
            ),
        ),
    ]
